# Generated by Django 5.2.4 on 2025-07-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
