# Generated by Django 5.2.4 on 2025-07-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_balanceitem_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balanceitem',
            options={'verbose_name': 'Статья баланса', 'verbose_name_plural': 'Статьи баланса'},
        ),
    ]
