# Generated by Django 5.2.4 on 2025-07-15 05:54

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_balanceitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancegroup',
            options={'verbose_name': 'Балансовые группы', 'verbose_name_plural': 'Балансовая группа'},
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='account',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.balancegroup', verbose_name='Балансовая группа'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование счёта'),
        ),
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(default=core.models.generate_account_number, max_length=10, unique=True, verbose_name='Номер счёта'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('active', 'Актив'), ('passive', 'Пассив'), ('both', 'Активно-пассивный')], max_length=10, verbose_name='Тип счёта'),
        ),
        migrations.AlterField(
            model_name='balancegroup',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.balanceitem', verbose_name='Статья баланса'),
        ),
        migrations.AlterField(
            model_name='balancegroup',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование группы'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='credit_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='core.account', verbose_name='Кредит'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debit_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_transactions', to='core.account', verbose_name='Дебет'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Аннулирована'),
        ),
    ]
